### ISSUE TITLE
When npm run dev, print out absolute path

### ISSUE THREAD

**Issue by cluelessjoe** [HeroesDesk/heroesdesk-front-web#4]
Currently when running npm run dev, the paths are displayed this way:
Building web app from /Users/foo/dev/heroesdesk-front-web/src/server/../../src/main//js/ to /Users/foo/dev/heroesdesk-front-web/src/server/../../www/

It comes from build.js:
  console.log("Building web app from " + srcPath + " to " + webAppPath);
Absolute paths would be better :)

**Comment by o-schneider** [comment]
Solved by 69470d307c8cc54639e87b8486ac740dba5c52fb
